language: go
go_import_path: github.com/kevinburke/handlers

os: linux
dist: trusty

before_script:
  - go get -t ./...

go:
  - tip
  - 1.15.x
  - 1.14.x

script:
  - make race-test

cache:
  directories:
    - $GOPATH/pkg
