language: go
go_import_path: github.com/kevinburke/handlers

os: linux
dist: trusty

sudo: required

before_script:
     - wget "https://storage.googleapis.com/bazel-apt/pool/jdk1.8/b/bazel/bazel_0.5.4_amd64.deb"
     - sudo dpkg --force-all -i bazel_0.5.4_amd64.deb
     - sudo apt-get install moreutils -y

script:
  - make ci
