on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: WillAbides/setup-go-faster@main
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
      with:
         path: './src/github.com/kevinburke/handlers'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
        echo "GO111MODULE=off" >> $GITHUB_ENV
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/kevinburke/handlers'
