on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x, 1.26.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: WillAbides/setup-go-faster@main
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v6
    - name: Run tests
      run: make ci
